# Generates C++ constant headers from the normative JSON sources at configure time:
#   protocol/registry.json -> gen/registry.hpp  (enums, limits, sizes; cross-checked against api/leanmesh.h)
#   config/profiles.json   -> gen/profiles.hpp  (per-role capacity tables)
#   config/defaults.json   -> gen/defaults.hpp  (initial policy values, nested namespaces)
#   tests/golden.json, tests/power_golden.json -> gen/golden.hpp (test builds only)
# Numbers are never copied by hand into C++; change the JSON and reconfigure.
# Shared by the native build (CMakeLists.txt) and the IDF component (components/leanmesh).
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/lm_pins.cmake")

# UPPER_SNAKE -> UpperCamel (e.g. HOP_ACK -> HopAck, OBJECT_4K -> Object4k).
function(lm_camel in out)
    string(TOLOWER "${in}" low)
    string(REPLACE "_" ";" parts "${low}")
    set(res "")
    foreach(p IN LISTS parts)
        string(SUBSTRING "${p}" 0 1 first)
        string(TOUPPER "${first}" first)
        string(SUBSTRING "${p}" 1 -1 rest)
        string(APPEND res "${first}${rest}")
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

# Writes only when the content changed, so unchanged headers do not trigger rebuilds.
function(lm_write_if_changed path content)
    set(tmp "${path}.tmp")
    file(WRITE "${tmp}" "${content}")
    configure_file("${tmp}" "${path}" COPYONLY)
    file(REMOVE "${tmp}")
endfunction()

# Emits `enum class <name> : <type> { ... };` from a JSON object {"NAME": value}.
function(lm_gen_enum json key enum_name underlying camel out_var)
    string(JSON n LENGTH "${json}" ${key})
    set(body "enum class ${enum_name} : ${underlying} {\n")
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" ${key} ${i})
        string(JSON v GET "${json}" ${key} ${k})
        if(camel)
            lm_camel("${k}" k)
        endif()
        string(APPEND body "    ${k} = ${v},\n")
    endforeach()
    string(APPEND body "};\n")
    set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(lm_gen_registry json out)
    set(h "// GENERATED from protocol/registry.json by cmake/lm_generate.cmake. Do not edit.\n")
    string(APPEND h "#pragma once\n#include <array>\n#include <cstddef>\n#include <cstdint>\n#include \"leanmesh.h\"\n\n")
    string(APPEND h "namespace lm::gen {\n\n")
    foreach(scalar spec_version wire_version abi_version)
        string(JSON v GET "${json}" ${scalar})
        string(JSON t TYPE "${json}" ${scalar})
        if(t STREQUAL "STRING")
            string(APPEND h "inline constexpr const char* k_${scalar} = \"${v}\";\n")
        else()
            string(APPEND h "inline constexpr uint32_t k_${scalar} = ${v};\n")
        endif()
    endforeach()
    string(APPEND h "static_assert(k_abi_version == LM_ABI_VERSION, \"registry abi_version != leanmesh.h\");\n\n")

    string(APPEND h "namespace limits {\n")
    string(JSON n LENGTH "${json}" limits)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" limits ${i})
        string(JSON v GET "${json}" limits ${k})
        string(APPEND h "inline constexpr uint32_t ${k} = ${v};\n")
    endforeach()
    string(APPEND h "}  // namespace limits\n")
    string(APPEND h "static_assert(limits::root_depth == LM_MAX_ROOT_DEPTH && limits::path_hops == LM_MAX_PATH_HOPS &&\n"
                    "              limits::rf_body_bytes == LM_MAX_RF_BYTES &&\n"
                    "              limits::small_message_bytes == LM_MAX_MESSAGE_BYTES &&\n"
                    "              limits::object_bytes == LM_MAX_OBJECT_BYTES, \"registry limits != leanmesh.h\");\n\n")

    # Status is [[nodiscard]]: every function returning it must be checked (docs/15 §2).
    lm_gen_enum("${json}" status_codes Status uint32_t TRUE e)
    string(REPLACE "enum class Status" "enum class [[nodiscard]] Status" e "${e}")
    string(APPEND h "${e}")
    string(JSON n LENGTH "${json}" status_codes)
    math(EXPR last "${n} - 1")
    set(names "")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" status_codes ${i})
        lm_camel("${k}" c)
        string(APPEND h "static_assert(static_cast<uint32_t>(Status::${c}) == LM_STATUS_${k}, \"${k}\");\n")
        string(APPEND names "        case Status::${c}: return \"${k}\";\n")
    endforeach()
    string(APPEND h "inline constexpr uint32_t k_status_count = ${n};\n")
    string(APPEND h "// Registry spelling; for diagnostics and tests, never parsed back.\n")
    string(APPEND h "constexpr const char* status_name(Status s) {\n    switch (s) {\n${names}    }\n")
    string(APPEND h "    return \"UNKNOWN\";\n}\n\n")

    lm_gen_enum("${json}" frame_kinds FrameKind uint8_t TRUE e)
    string(APPEND h "${e}\n")
    lm_gen_enum("${json}" record_kinds RecordKind uint8_t TRUE e)
    string(APPEND h "${e}\n")
    lm_gen_enum("${json}" control_types ControlType uint8_t FALSE e)
    string(APPEND h "${e}\n")
    lm_gen_enum("${json}" serial_kinds SerialKind uint8_t TRUE e)
    string(APPEND h "${e}\n")
    lm_gen_enum("${json}" capability_bits CapabilityBit uint8_t TRUE e)
    string(APPEND h "${e}")
    string(JSON n LENGTH "${json}" capability_bits)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" capability_bits ${i})
        string(JSON v GET "${json}" capability_bits ${k})
        string(APPEND h "static_assert((UINT64_C(1) << ${v}) == LM_FEATURE_${k}, \"${k}\");\n")
    endforeach()
    string(APPEND h "\n")

    foreach(list_key signed_control_types reserved_control_types)
        string(JSON n LENGTH "${json}" ${list_key})
        set(items "")
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            string(JSON v GET "${json}" ${list_key} ${i})
            list(APPEND items "${v}")
        endforeach()
        string(REPLACE ";" ", " items "${items}")
        string(APPEND h "inline constexpr std::array<uint8_t, ${n}> k_${list_key}{${items}};\n")
    endforeach()
    string(APPEND h "\n")

    # Fixed binary layouts: total byte sizes and field offsets.
    string(APPEND h "namespace layout {\n")
    foreach(layout link route end)
        string(JSON bytes GET "${json}" fields ${layout} bytes)
        string(APPEND h "namespace ${layout} {\ninline constexpr std::size_t bytes = ${bytes};\n")
        string(JSON n LENGTH "${json}" fields ${layout} items)
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            string(JSON name GET "${json}" fields ${layout} items ${i} name)
            string(JSON off GET "${json}" fields ${layout} items ${i} offset)
            string(JSON size GET "${json}" fields ${layout} items ${i} size)
            string(APPEND h "inline constexpr std::size_t ${name}_offset = ${off}, ${name}_size = ${size};\n")
        endforeach()
        string(APPEND h "}  // namespace ${layout}\n")
    endforeach()
    string(JSON poll_bytes GET "${json}" power_frames poll bytes)
    string(JSON grant_bytes GET "${json}" power_frames grant bytes)
    string(APPEND h "inline constexpr std::size_t power_poll_bytes = ${poll_bytes};\n")
    string(APPEND h "inline constexpr std::size_t power_grant_bytes = ${grant_bytes};\n")
    string(APPEND h "}  // namespace layout\n\n")

    string(APPEND h "namespace aead {\n")
    foreach(k tag_bytes key_bytes nonce_prefix_bytes counter_bytes)
        string(JSON v GET "${json}" aead ${k})
        string(APPEND h "inline constexpr std::size_t ${k} = ${v};\n")
    endforeach()
    foreach(k method suite exporter_label)
        string(JSON v GET "${json}" aead edhoc ${k})
        string(APPEND h "inline constexpr uint32_t edhoc_${k} = ${v};\n")
    endforeach()
    string(JSON v GET "${json}" session_binding timeout_ms)
    string(APPEND h "inline constexpr uint32_t session_bind_timeout_ms = ${v};\n")
    string(JSON v GET "${json}" session_binding max_attempts)
    string(APPEND h "inline constexpr uint32_t session_bind_max_attempts = ${v};\n")
    string(APPEND h "}  // namespace aead\n\n}  // namespace lm::gen\n")
    lm_write_if_changed("${out}" "${h}")
endfunction()

function(lm_gen_profiles json out)
    set(h "// GENERATED from config/profiles.json by cmake/lm_generate.cmake. Do not edit.\n")
    string(APPEND h "// Values are design targets, not measurements (profiles.json \"status\").\n")
    string(APPEND h "#pragma once\n#include <cstdint>\n\nnamespace lm::gen {\n\nstruct ProfileLimits {\n")
    string(JSON n LENGTH "${json}" profiles leaf)
    math(EXPR last "${n} - 1")
    set(keys "")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" profiles leaf ${i})
        string(JSON t TYPE "${json}" profiles leaf ${k})
        list(APPEND keys "${k}")
        if(t STREQUAL "BOOLEAN")
            string(APPEND h "    bool ${k};\n")
        else()
            string(APPEND h "    uint32_t ${k};\n")
        endif()
    endforeach()
    string(APPEND h "};\n\n")
    foreach(role leaf relay root)
        string(JSON rn LENGTH "${json}" profiles ${role})
        if(NOT rn EQUAL n)
            message(FATAL_ERROR "config/profiles.json: profile '${role}' has different keys than 'leaf'")
        endif()
        string(APPEND h "inline constexpr ProfileLimits k_profile_${role}{\n")
        foreach(k IN LISTS keys)
            string(JSON v GET "${json}" profiles ${role} ${k})
            if(v STREQUAL "ON")
                set(v true)
            elseif(v STREQUAL "OFF")
                set(v false)
            endif()
            string(APPEND h "    ${v},  // ${k}\n")
        endforeach()
        string(APPEND h "};\n")
    endforeach()
    string(APPEND h "\n}  // namespace lm::gen\n")
    lm_write_if_changed("${out}" "${h}")
endfunction()

# Recursive JSON object -> nested namespaces of constexpr values.
function(lm_gen_defaults_object json path indent out_var)
    set(body "")
    string(JSON n LENGTH "${json}" ${path})
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON k MEMBER "${json}" ${path} ${i})
        string(JSON t TYPE "${json}" ${path} ${k})
        string(JSON v GET "${json}" ${path} ${k})
        if(t STREQUAL "OBJECT")
            lm_gen_defaults_object("${json}" "${path};${k}" "${indent}" sub)
            string(APPEND body "namespace ${k} {\n${sub}}  // namespace ${k}\n")
        elseif(t STREQUAL "NUMBER")
            string(APPEND body "inline constexpr uint64_t ${k} = ${v}u;\n")
        elseif(t STREQUAL "BOOLEAN")
            if(v)
                string(APPEND body "inline constexpr bool ${k} = true;\n")
            else()
                string(APPEND body "inline constexpr bool ${k} = false;\n")
            endif()
        elseif(t STREQUAL "STRING")
            string(APPEND body "inline constexpr const char* ${k} = \"${v}\";\n")
        elseif(t STREQUAL "NULL")
            string(APPEND body "// ${k}: null in defaults.json (must be provided by a deployment profile)\n")
        elseif(t STREQUAL "ARRAY")
            string(JSON an LENGTH "${json}" ${path} ${k})
            set(items "")
            if(an GREATER 0)
                math(EXPR alast "${an} - 1")
                foreach(j RANGE ${alast})
                    string(JSON av GET "${json}" ${path} ${k} ${j})
                    list(APPEND items "${av}u")
                endforeach()
            endif()
            string(REPLACE ";" ", " items "${items}")
            string(APPEND body "inline constexpr std::array<uint64_t, ${an}> ${k}{${items}};\n")
        endif()
    endforeach()
    set(${out_var} "${body}" PARENT_SCOPE)
endfunction()

function(lm_gen_defaults json out)
    set(h "// GENERATED from config/defaults.json by cmake/lm_generate.cmake. Do not edit.\n")
    string(APPEND h "// Initial settings (\"初期設定\"), not measurements. Runtime policy may override within bounds.\n")
    string(APPEND h "#pragma once\n#include <array>\n#include <cstdint>\n\nnamespace lm::gen::defaults {\n")
    lm_gen_defaults_object("${json}" "" "" body)
    string(APPEND h "${body}}  // namespace lm::gen::defaults\n")
    lm_write_if_changed("${out}" "${h}")
endfunction()

function(lm_gen_golden golden power out)
    set(h "// GENERATED from tests/golden.json and tests/power_golden.json. PUBLIC TEST DATA ONLY.\n")
    string(APPEND h "// Never link into product images.\n#pragma once\n\nnamespace lm::gen::golden {\n\n")
    string(APPEND h "struct Frame {\n    const char* name;\n    unsigned hops;\n")
    set(fkeys link_context_hex end_context_hex link_exporter_test_seed_hex end_exporter_test_seed_hex
              packet_hex payload_hex intent_hash packet_sha256)
    foreach(k IN LISTS fkeys)
        string(APPEND h "    const char* ${k};\n")
    endforeach()
    string(APPEND h "};\n\ninline constexpr Frame k_frames[] = {\n")
    string(JSON n LENGTH "${golden}" frames)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON name GET "${golden}" frames ${i} name)
        string(JSON hops GET "${golden}" frames ${i} hops)
        string(APPEND h "    {\"${name}\", ${hops}")
        foreach(k IN LISTS fkeys)
            string(JSON v GET "${golden}" frames ${i} ${k})
            string(APPEND h ",\n     \"${v}\"")
        endforeach()
        string(APPEND h "},\n")
    endforeach()
    string(APPEND h "};\n\nnamespace cose {\n")
    foreach(k cose_key_hex device_id_hex protected_hex payload_hex sig_structure_hex signature_raw_hex
              cose_sign1_hex)
        string(JSON v GET "${golden}" cose_sign1 ${k})
        string(APPEND h "inline constexpr const char* ${k} = \"${v}\";\n")
    endforeach()
    string(APPEND h "}  // namespace cose\n\nnamespace power {\n")
    foreach(k poll_hex grant_hex)
        string(JSON v GET "${power}" ${k})
        string(APPEND h "inline constexpr const char* ${k} = \"${v}\";\n")
    endforeach()
    string(APPEND h "}  // namespace power\n\n}  // namespace lm::gen::golden\n")
    lm_write_if_changed("${out}" "${h}")
endfunction()

# Public entry point. Generates product headers into <out_dir>/gen/, and the golden header when
# with_golden is TRUE (native test builds only).
function(lm_generate_headers out_dir with_golden)
    set(sources "${LM_REPO_ROOT}/protocol/registry.json" "${LM_REPO_ROOT}/config/profiles.json"
                "${LM_REPO_ROOT}/config/defaults.json")
    file(READ "${LM_REPO_ROOT}/protocol/registry.json" registry)
    file(READ "${LM_REPO_ROOT}/config/profiles.json" profiles)
    file(READ "${LM_REPO_ROOT}/config/defaults.json" defaults)
    lm_gen_registry("${registry}" "${out_dir}/gen/registry.hpp")
    lm_gen_profiles("${profiles}" "${out_dir}/gen/profiles.hpp")
    lm_gen_defaults("${defaults}" "${out_dir}/gen/defaults.hpp")
    if(with_golden)
        file(READ "${LM_REPO_ROOT}/tests/golden.json" golden)
        file(READ "${LM_REPO_ROOT}/tests/power_golden.json" power)
        lm_gen_golden("${golden}" "${power}" "${out_dir}/gen/golden.hpp")
        list(APPEND sources "${LM_REPO_ROOT}/tests/golden.json" "${LM_REPO_ROOT}/tests/power_golden.json")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${sources})
endfunction()
